apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo        # Default GKE disk
  resources:
    requests:
      storage: 1Gi