apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-production
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/ShehzadKhuwaja/Kubernetes-With-MOOC.git
    targetRevision: HEAD
    path: 1.2/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Only sync when a tag is pushed
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/annotations
