apiVersion: argoproj.io/v1alpha1
kind:  Application
metadata:
  name:  todoapp-production
  namespace:  argocd
  finalizers: 
    - resources-finalizer. argocd.argoproj. io
spec:
  project:  default
  
  source: 
    repoURL: https://github.com/ShehzadKhuwaja/Kubernetes-With-MOOC-config.git
    targetRevision: main
    path: overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff: 
        duration: 5s
        factor: 2
        maxDuration: 3m